# version: '4'
services:
  mongodb:
    image: mongo:7.0.5
    container_name : mongodb
    ports:
      - "27017:27017"
    environment:
        MONGO_INIT_ROOT_USERNAME : root
        MONGO_INIT_ROOT_PASSWORD : password
        MONGO_INITDB_DATABASE : patients_service
    volumes:
      - ./data:/data/db
