# Stage 1: Build the application (this stage is no longer needed if you're copying a pre-built JAR)
# FROM maven:3.8-openjdk-17-slim AS builder

# Stage 2: Run the application
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the pre-built JAR file from the local machine into the container
# Assuming your JAR file is located in the target directory
COPY ./target/*.jar /app/app.jar
# COPY ./docker-compose.yml /app/docker-compose.yml
# RUN "docker compose up"
# Expose the port that your Spring Boot application will run on (default is 8080)
# EXPOSE 8080

# Command to run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
